spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        discriminator:
          ignore_explicit_for_joined: false
        format_sql: true
        default_batch_fetch_size: 500
        globally_quoted_identifiers: true
    open-in-view: false

  config:
    activate:
      on-profile:
        - dev
        - local